2014-09-22 18:15:54,746:INFO    :root                :MainThread     : Root log configured. (boot.configure_logger() @458)
2014-09-22 18:15:54,746:DEBUG   :__main__            :MainThread     : Running Python 3.4.1.final.0 from /Library/Frameworks/Python.framework/Versions/3.4/bin/python3 (boot.load_isolate() @118)
2014-09-22 18:15:54,747:DEBUG   :__main__            :MainThread     : Starting Pelix framework with properties:
{'cohorte.base': '/Users/debbabi/dev/github/cohorte-community/demos/spellchecker/platforms/base',
 'cohorte.configuration.broker.url': 'http://[::]:8000/cohorte/broker/f1e6e214-8e22-4944-8a4b-fbd34802a8c2',
 'cohorte.debug': True,
 'cohorte.home': '/Users/debbabi/dev/github/cohorte-community/platforms/home',
 'cohorte.isolate.uid': 'f1e6e214-8e22-4944-8a4b-fbd34802a8c2',
 'cohorte.log.color': False,
 'cohorte.state.updater.url': 'http://[::]:8000/cohorte/state-updater',
 'cohorte.verbose': True,
 'framework.uid': 'f1e6e214-8e22-4944-8a4b-fbd34802a8c2',
 'pelix.debug': True} (boot.load_isolate() @120)
2014-09-22 18:15:54,747:DEBUG   :__main__            :MainThread     : Installing bundle pelix.ipopo.core... (boot._run_framework() @207)
2014-09-22 18:15:54,751:DEBUG   :__main__            :MainThread     : Bundle pelix.ipopo.core (1) started (boot._run_framework() @211)
2014-09-22 18:15:54,751:DEBUG   :__main__            :MainThread     : Installing bundle cohorte.config.finder... (boot._run_framework() @207)
2014-09-22 18:15:54,754:DEBUG   :__main__            :MainThread     : Bundle cohorte.config.finder (6) started (boot._run_framework() @211)
2014-09-22 18:15:54,754:DEBUG   :__main__            :MainThread     : Installing bundle cohorte.config.reader... (boot._run_framework() @207)
2014-09-22 18:15:54,758:DEBUG   :__main__            :MainThread     : Bundle cohorte.config.reader (7) started (boot._run_framework() @211)
2014-09-22 18:15:54,758:DEBUG   :__main__            :MainThread     : Installing bundle cohorte.config.parser... (boot._run_framework() @207)
2014-09-22 18:15:54,762:DEBUG   :__main__            :MainThread     : Bundle cohorte.config.parser (8) started (boot._run_framework() @211)
2014-09-22 18:15:54,762:DEBUG   :__main__            :MainThread     : Using isolate loader: cohorte.boot.loaders.broker. (boot._run_framework() @223)
2014-09-22 18:15:54,796:DEBUG   :__main__            :MainThread     : Instantiating component of type 'cohorte-loader-broker-factory' (boot._get_loader() @87)
2014-09-22 18:15:54,797:DEBUG   :__main__            :MainThread     : Isolate booting... (boot._run_framework() @229)
2014-09-22 18:15:54,806:DEBUG   :cohorte.boot.loaders.broker:MainThread     : Using boot configuration from the broker (broker.load() @297)
2014-09-22 18:15:54,907:INFO    :pelix.shell.core    :MainThread     : Shell services registered (core.start() @1485)
2014-09-22 18:15:54,921:INFO    :pelix.shell.remote  :MainThread     : RemoteShell validated on port: 56094 (remote.validate() @370)
2014-09-22 18:15:54,922:INFO    :cohorte.debug.servlet:MainThread     : Debug servlet Ready (servlet.validate() @344)
2014-09-22 18:15:54,943:INFO    :pelix-http-service  :MainThread     : Starting HTTP server: [::]:0 ... (basic.log() @707)
2014-09-22 18:15:54,944:INFO    :pelix-http-service  :MainThread     : HTTP server started: [::]:56095 (basic.log() @707)
2014-09-22 18:15:54,947:DEBUG   :herald.core         :MainThread     : No peer to send the message to. (core.fire_group() @712)
2014-09-22 18:15:54,952:ERROR   :InstanceManager-cohorte-isolate-agent:MainThread     : Component 'cohorte-isolate-agent' : error calling callback method for event VALIDATE (instance.__safe_callback() @509)
Traceback (most recent call last):
  File "/Users/debbabi/dev/github/cohorte-community/platforms/home/lib/pelix/ipopo/instance.py", line 489, in __safe_callback
    return self.__callback(event, *args, **kwargs)
  File "/Users/debbabi/dev/github/cohorte-community/platforms/home/lib/pelix/ipopo/instance.py", line 439, in __callback
    result = comp_callback(self.instance, *args, **kwargs)
  File "/Users/debbabi/dev/github/cohorte-community/platforms/home/lib/cohorte/monitor/agent.py", line 95, in validate
    self._sender.fire_group('monitors', message)
  File "/Users/debbabi/dev/github/cohorte-community/platforms/home/lib/herald/core.py", line 659, in fire_group
    all_peers = self._directory.get_peers_for_group(group)
  File "/Users/debbabi/dev/github/cohorte-community/platforms/home/lib/herald/directory.py", line 314, in get_peers_for_group
    return self._groups[group].copy()
KeyError: 'monitors'
2014-09-22 18:15:54,964:DEBUG   :__main__            :MainThread     : Isolate loaded. (boot._run_framework() @247)
2014-09-22 18:15:54,964:DEBUG   :__main__            :MainThread     : Waiting for the isolate to stop... (boot._run_framework() @250)
2014-09-22 18:15:55,053:ERROR   :InstanceManager-dictionary_en_python:HeraldNotify-2 : Component 'dictionary_en_python' : error calling callback method for event VALIDATE (instance.__safe_callback() @509)
Traceback (most recent call last):
  File "/Users/debbabi/dev/github/cohorte-community/platforms/home/lib/pelix/ipopo/instance.py", line 489, in __safe_callback
    return self.__callback(event, *args, **kwargs)
  File "/Users/debbabi/dev/github/cohorte-community/platforms/home/lib/pelix/ipopo/instance.py", line 439, in __callback
    result = comp_callback(self.instance, *args, **kwargs)
  File "/Users/debbabi/dev/github/cohorte-community/demos/spellchecker/platforms/base/repo/spellchecker/spell_dictionary_EN.py", line 41, in validate
    os.rename("dictionary_en.txt", "dictionary_en.py")
FileNotFoundError: [Errno 2] No such file or directory: 'dictionary_en.txt' -> 'dictionary_en.py'
2014-09-22 18:15:55,055:ERROR   :InstanceManager-dictionary_fr_python:HeraldNotify-2 : Component 'dictionary_fr_python' : error calling callback method for event VALIDATE (instance.__safe_callback() @509)
Traceback (most recent call last):
  File "/Users/debbabi/dev/github/cohorte-community/platforms/home/lib/pelix/ipopo/instance.py", line 489, in __safe_callback
    return self.__callback(event, *args, **kwargs)
  File "/Users/debbabi/dev/github/cohorte-community/platforms/home/lib/pelix/ipopo/instance.py", line 439, in __callback
    result = comp_callback(self.instance, *args, **kwargs)
  File "/Users/debbabi/dev/github/cohorte-community/demos/spellchecker/platforms/base/repo/spellchecker/spell_dictionary_FR.py", line 42, in validate
    os.rename("dictionary_fr.txt", "dictionary_fr.py")
FileNotFoundError: [Errno 2] No such file or directory: 'dictionary_fr.txt' -> 'dictionary_fr.py'
